### ISSUE TITLE
Wrong setting in docs examples

### ISSUE THREAD

**Issue by AlexMarlo** [jonasfranz/drone-crowdin#5]
Where: https://github.com/jonasfranz/drone-crowdin/blob/master/DOCS.md

Current:
```
pipeline:
  crowdin:
    image: jonasfranz/crowdin
    project_identifier: example
    project_key: 1bc29b36f623ba82aaf6724fd3b16718
    files:
      example: options/example.ini
      example2: options/example2.ini
```

Should be 
```
pipeline:
  crowdin:
    image: jonasfranz/crowdin
    settings:
      project_identifier: example
      project_key: 1bc29b36f623ba82aaf6724fd3b16718
      files:
        example: options/example.ini
        example2: options/example2.ini
```
